lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.description, name="about"),
    path("thanks", views.redirect_feedback, name="thanks_for_feedback"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.main, name="main"),
    path("coffee/", views.coffee, name="coffee"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("about/", include("about.urls")),
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/users/urls.py
from django.contrib.auth import views
from django.urls import path

from users import views as users_views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.register,
        name="signup",
    ),
    path(
        "activate/<username>/",
        users_views.activate,
        name="activate",
    ),
    path(
        "user_list/",
        users_views.user_list,
        name="user_list",
    ),
    path(
        "user_detail/<int:user_id>/",
        users_views.user_detail,
        name="user_detail",
    ),
    path(
        "profile/",
        users_views.profile,
        name="profile",
    ),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

lyceum/users/models.py
from django.contrib.auth.models import User as DjangoUser
from django.db import models


__all__ = []


class Profile(models.Model):
    def upload_to(self, filename):
        return f"avatars/{self.pk}_{filename}"

    user = models.OneToOneField(
        DjangoUser,
        on_delete=models.CASCADE,
    )

    birthday = models.DateField(
        verbose_name="день рождение",
        help_text="формата: день:месяц:год",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to=upload_to,
        verbose_name="аватар",
        blank=True,
        null=True,
    )

    coffee_count = models.PositiveIntegerField(
        verbose_name="кофе сварено",
        default=0,
    )

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"


class DjangoUserManager(models.Manager):
    use_in_migrations = True
    username = DjangoUser.username.field.name
    first_name = DjangoUser.first_name.field.name
    last_name = DjangoUser.last_name.field.name
    email = DjangoUser.email.field.name
    date_joined = DjangoUser.date_joined.field.name
    last_login = DjangoUser.last_login.field.name
    is_superuser = DjangoUser.is_superuser.field.name
    is_staff = DjangoUser.is_staff.field.name
    is_active = DjangoUser.is_active.field.name

    birthday = "profile__birthday"
    image = "profile__image"
    coffee_count = "profile__coffee_count"

    def load_profile_data(self, user):
        return super().get_queryset().select_related("profile").get(id=user.pk)

    def active(self):
        return super().select_related("profile").filter(is_active=True)

    def by_mail(self, email):
        return super().get(email=email)

    def full_user_data(self, user):
        return super().select_related("profile").get(id=user.pk)


class User(DjangoUser):
    objects = DjangoUserManager()

    DjangoUser._meta.get_field("email")._unique = True

    class Meta:
        proxy = True
        managed = False

lyceum/users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from users.models import Profile

__all__ = []


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )
        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "required": True,
                },
            ),
        }


class UserForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    password = None

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            User.first_name.field.name,
            User.last_name.field.name,
            User.email.field.name,
        )
        exclude = (User.password.field.name,)


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Profile
        fields = (
            Profile.birthday.field.name,
            Profile.image.field.name,
            Profile.coffee_count.field.name,
        )

        widgets = {
            Profile.coffee_count.field.name: forms.NumberInput(
                attrs={
                    "disabled": True,
                },
            ),
        }


class EditProfile(forms.Form):
    profile = ProfileForm()
    user = UserForm()


class CoffeeBlob(forms.Form):
    pass

lyceum/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import get_list_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone


from users.forms import EditProfile, ProfileForm, RegisterForm, UserForm
from users.models import Profile, User

PATH = "users/"

__all__ = []


def register(request):
    context = {}
    template = PATH + "signup.html"
    form = RegisterForm(request.POST or None)
    context["form"] = form
    if False not in (form.is_valid(), request.method == "POST"):
        formclean = form.cleaned_data
        username = formclean.get("username")
        email = formclean.get("email")
        if User.objects.filter(username=username).first():
            context["form"].add_error(
                "username",
                "Пользователь с таким именем уже существует!",
            )

        if User.objects.filter(email=email).first():
            context["form"].add_error(
                "email",
                "Пользователь с такой почтой уже существует!",
            )
        if context["form"].has_error("email") or context["form"].has_error(
            "username",
        ):
            return render(request, template, context)
        user = form.save(commit=False)
        user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        user.save()
        Profile.objects.create(user=user)
        messages.success(
            request,
            "Профиль успешно сохранён! Теперь подтвердите его!",
        )

        send_mail(
            "Активация",
            f"http://{request.get_host()}/auth/activate/{username}/",
            from_email=settings.DJANGO_MAIL,
            recipient_list=[email],
            fail_silently=False,
        )
        context["form"] = RegisterForm(None)
        return render(request, template, context)
    return render(request, template, context)


def activate(request, username):
    template = PATH + "activate_user.html"
    context = {}
    user = User.objects.get(username=username)
    date_activate = user.date_joined + timezone.timedelta(hours=12)
    if (
        date_activate.timestamp() <= timezone.now().timestamp()
    ) and not user.is_active:
        user.is_active = True
        user.save()
        context["status"] = "Аккаунт активирован!"
        context["class"] = "bg-success"
    else:
        context["status"] = (
            "Аккаунт уже активирован или не прошло"
            " 12 часов с момента создания аккаунта!"
        )
        context["class"] = "bg-danger"
    return render(request, template, context)


def user_list(request):
    template = PATH + "user_list.html"
    context = {}

    users = get_list_or_404(User.objects.active())
    context["users"] = users
    return render(request, template, context)


def user_detail(request, user_id):
    template = PATH + "user_detail.html"
    context = {}
    if request.user.id == user_id:
        return redirect(reverse("users:profile"))
    user = User.objects.filter(id=user_id).first()
    context["user"] = user
    return render(request, template, context)


@login_required
def profile(request):
    template = PATH + "profile.html"
    context = {}
    form_user = UserForm(
        request.POST or None,
        instance=request.user,
    )
    form_profile = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=request.user.profile,
    )

    if False not in (
        form_user.is_valid(),
        form_profile.is_valid(),
        "change" in request.POST,
        request.method == "POST",
    ):
        form_user.save()
        form_profile.save()

    form = EditProfile()
    form.user = form_user
    form.profile = form_profile

    context["user"] = request.user
    context["form"] = form
    return render(request, template, context)

lyceum/templates/users/activate_user.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1 class="badge {{class}}">{{status}}</h1>
</main>
{% endblock content %}

lyceum/templates/users/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1>Вход</h1>
    {% for message in messages %}
        {% if 'success' in message.tags %}
          <div class="success-message">{{ message }}</div>
        {% endif %}
      {% endfor %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3 border border-success bg-secondary">
                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                        <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                            {{field}}
                            <h6>{{field.help_text}}</h6>
                            {% if form.errors %}
                                <span class="help-inline">
                                    {% for error in field.errors %}
                                        <div class="text-warning">
                                            {{ error|escape }}
                                        </div> 
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <input type="submit" value="войти" title="вход в аккаунт"/><br>
            <a href="{% url "users:password_reset" %}">Забыли пароль?</a><br>
            <a href="{% url "users:signup" %}">Не зарегистрированы?</a>
        </div>
    </form>
    
</main>
{% endblock content %}

lyceum/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <main class="container text-center">
    <h1 class="badge bg-success">Письмо отправлено</h1>

    <div class="border bg-secondary">
      <h5 class="text-info">Вы успешно вышлАи из аккаунта<br /></h5>
    </div>
  </main>
{% endblock %}

lyceum/templates/users/password_change.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1>Сброс пароля</h1>
    {% for message in messages %}
        {% if 'success' in message.tags %}
          <div class="success-message">{{ message }}</div>
        {% endif %}
      {% endfor %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3 border border-success bg-secondary">
                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                        <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                            {{field}}
                            <h6>{{field.help_text}}</h6>
                            {% if form.errors %}
                                <span class="help-inline">
                                    {% for error in field.errors %}
                                        <div class="text-warning">
                                            {{ error|escape }}
                                        </div> 
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <input type="submit" value="сменить" title="вход в аккаунт"/>
        </div>
    </form>
</main>
{% endblock content %}

lyceum/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <main class="container text-center">
    <h1 class="badge bg-success">Пароль успешно изменён</h1>

    <div class="border bg-secondary">
      <h5 class="text-info">Теперь вход выполняется под новым паролем!</h5>
    </div>
  </main>
{% endblock %}

lyceum/templates/users/password_reset.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1>Сброс пароля</h1>
    {% for message in messages %}
        {% if 'success' in message.tags %}
          <div class="success-message">{{ message }}</div>
        {% endif %}
    {% endfor %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3 border border-success bg-secondary">
                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                        <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                            {{field}}
                            <h6>{{field.help_text}}</h6>
                            {% if form.errors %}
                                <span class="help-inline">
                                    {% for error in field.errors %}
                                        <div class="text-warning">
                                            {{ error|escape }}
                                        </div> 
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <input type="submit" value="сбросить" title="вход в аккаунт"/>
        </div>
    </form>
</main>
{% endblock content %}

lyceum/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <main class="container text-center">
    <h1 class="badge bg-success">Письмо отправлено</h1>

    <div class="border">
      <h5>
        Письмо с инструкциями по восстановлению пароля отправлено<br />

        Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты <br> <span class="text-info">(если в нашей базе данных есть такой адрес) Вы должны получить ее в ближайшее время.</span>
      </h5>
      <h6 class="text-warning">Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</h6>
    </div>
  </main>
{% endblock %}

lyceum/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1>Сброс пароля</h1>
    {% for message in messages %}
        {% if 'success' in message.tags %}
          <div class="success-message">{{ message }}</div>
        {% endif %}
    {% endfor %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3 border border-success bg-secondary">
                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                        <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                            {{field}}
                            <h6>{{field.help_text}}</h6>
                            {% if form.errors %}
                                <span class="help-inline">
                                    {% for error in field.errors %}
                                        <div class="text-warning">
                                            {{ error|escape }}
                                        </div> 
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <input type="submit" value="сбросить" title="вход в аккаунт"/>
        </div>
    </form>
</main>
{% endblock content %}

lyceum/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <main class="container text-center">
    <h1 class="badge bg-success">Письмо отправлено</h1>

    <div class="border">
      <h5>
        Письмо с инструкциями по восстановлению пароля отправлено<br />

        Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты <br> <span class="text-info">(если в нашей базе данных есть такой адрес) Вы должны получить ее в ближайшее время.</span>
      </h5>
      <h6 class="text-warning">Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</h6>
    </div>
  </main>
{% endblock %}

lyceum/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <div class="container">
    <div class="row gutters-sm mt-3">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="/media/{{ request.user.profile.image }}" alt="Картинки нет!" class="img-thumbnail border border-primary rounded" />
              <div class="mt-3">
                <h4>О себе:</h4>
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline">
                  <circle cx="12" cy="12" r="10"></circle>
                  <line x1="2" y1="12" x2="22" y2="12"></line>
                  <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                </svg>Сайт
              </h6>
              <span class="text-secondary">http://127.0.0.1/</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Имя и Фамилия</h6>
              </div>
              <span class="col-sm-9 text-secondary" style="font-family: 'Arial', sans-serif;">{{ request.user.first_name|default:'неуказано' }} {{ request.user.last_name|default:'неуказано' }}</span>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Почта</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{ request.user.email }}</div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">День рождения</h6>
              </div>
              <div class="col-sm-9 text-secondary" style="font-family: 'Arial', sans-serif;">{{ request.user.profile.birthday|default:'неуказано' }}</div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Чашек кофе сварено</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{ user.profile.coffee_count }}</div>
            </div>
          </div>
          <div class="accordion text-center" id="accordionPanelsStayOpenExample">
            <div class="accordion-item">
              <h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">Редактирование профиля</button></h2>
              <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
                <div class="accordion-body">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mt-3 border border-success bg-secondary container">
                      {{ form.user.as_p }}
                      {{ form.profile.as_p }}
                      <button type="submit" name="change" title="изменение">изменение профиля</button>
                      <button type="submit" name="drink_coffee" title="кофеёк"><a href="{% url 'homepage:coffee' %}">выпить кофе</a></button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row gutters-sm">
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Статусбар</i></h6>
                <small>Статус А</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Статусбар</i></h6>
                <small>Статус Б</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 50%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

<!-- Взято с https://www.bootdey.com/ -->

lyceum/templates/users/signup.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<main class="container text-center">
    <h1>Создание аккаунта</h1>
    {% for message in messages %}
        {% if 'success' in message.tags %}
          <div class="success-message">{{ message }}</div>
        {% endif %}
      {% endfor %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3 border border-success bg-secondary">
                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                        <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                            {{field}}
                            <h6>{{field.help_text}}</h6>
                            {% if form.errors %}
                                <span class="help-inline">
                                    {% for error in field.errors %}
                                        <div class="text-warning">
                                            {{ error|escape }}
                                        </div> 
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <input type="submit" value="зарегистрироваться" title="вход в аккаунт"/><br />
            <a href="{% url "users:login" %}">Вы уже регистрировались ранее?</a>
        </div>
    </form>
</main>
{% endblock content %}

lyceum/templates/users/user_list.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <table class="table table-info table-hover container mt-1">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Ник</th>
        <th scope="col">Аккаунт создан</th>
        <th scope="col">Кофе сварено</th>
        <th scope="col">Аватар</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td style="font-family: 'Arial', sans-serif;">{{ user.first_name|default:"неуказано" }}</td>
          <td style="font-family: 'Arial', sans-serif;">{{ user.last_name|default:"неуказано" }}</td>
          <td><a class="text-dark" href="{% url "users:user_detail" user.pk %}">{{ user.username }}</a></td>
          <td>{{ user.date_joined }}</td>
          <td>{{ user.profile.coffee_count }}</td>
          <td><img src="/media/{% if user.profile.image %}{{ user.profile.image }}{% else %}images/first_rocket.jpg{% endif %}" class="border border-primary-subtle rounded" width="50px", height="50px"></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}