lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.description, name="about"),
    path("thanks", views.redirect_feedback, name="thanks_for_feedback"),
]

lyceum/catalog/urls.py
from django.urls import path, register_converter

from catalog import converters, views

register_converter(converters.NumConverter, "fnn")

app_name = "catalog"


urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("<int:num>/", views.item_detail, name="item_detail"),
    path("new/", views.new_item, name="new"),
    path("friday/", views.friday_item, name="friday"),
    path("unverified/", views.unverified_item, name="unverified"),
]

lyceum/feedback/urls.py
from django.urls import path

from feedback import views

app_name = "feedback"

urlpatterns = [
    path("", views.feedback, name="feedback"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.main, name="main"),
    path("coffee/", views.coffee, name="coffee"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("ckeditor", include("ckeditor_uploader.urls")),
    path("about/", include("about.urls")),
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/users/urls.py
from django.contrib.auth import views
from django.urls import path

from users import views as users_views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.register,
        name="signup",
    ),
    path(
        "activate/<username>/",
        users_views.activate,
        name="activate",
    ),
    path(
        "user_list/",
        users_views.user_list,
        name="user_list",
    ),
    path(
        "user_detail/<int:user_id>/",
        users_views.user_detail,
        name="user_detail",
    ),
    path(
        "profile/",
        users_views.profile,
        name="profile",
    ),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

lyceum/templates/includes/auth_form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mt-3 border border-success bg-secondary">
            {% for field in form %}
                <div class="control-group {% if field.errors %}error{% endif %}">
                    <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
                    <div class="controls" title="{% if field.field.required %}обязательное поле">* {% else %}"> {% endif %}
                        {{field}}
                        <h6>{{field.help_text}}</h6>
                        {% if form.errors %}
                            <span class="help-inline">
                                {% for error in field.errors %}
                                    <div class="text-warning">
                                        {{ error|escape }}
                                    </div> 
                                {% endfor %}
                            </span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        <input type="submit" value="войти" title="вход в аккаунт"/>
    </div>
</form>

lyceum/templates/includes/footer.html
{% load static %}
<footer>
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="container">
      <div class="col-md-4 d-flex align-items-center">
        <a class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1"><svg class="bi" width="30" height="24"></svg></a>
        <span class="text-info">© PEPE, django</span>
      </div>
      <div class="text-info me-2 lh-1">
        <svg class="bi" width="30" height="24"></svg>
        <span id="year">{% now "Y" %}</span>
      </div>
    </div>
    <script>
      let get_id = document.getElementById('year')
      let now = new Date()
      let server_time = new Date("{% now "Y-m-d H:i" %}")
      if ((server_time.getHours() - now.getHours()) > -24) {
        get_id.textContent = server_time.getFullYear()
      } else {
        get_id.textContent = now.getFullYear()
      }
    </script>
  </footer>
</footer>

lyceum/templates/includes/header.html
<header>
  <div class="px-3 py-2 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        {% load i18n %}
        <title>{{ title_page }}</title>
        {% with request.resolver_match.view_name as view_name %}
          <nav class="nav">
            <svg width="25" height="25" fill="currentColor" class="bi bi-rocket-takeoff-fill" viewBox="0 0 20 20">
              <path d="M12.17 9.53c2.307-2.592 3.278-4.684 3.641-6.218.21-.887.214-1.58.16-2.065a3.578 3.578 0 0 0-.108-.563 2.22 2.22 0 0 0-.078-.23V.453c-.073-.164-.168-.234-.352-.295a2.35 2.35 0 0 0-.16-.045 3.797 3.797 0 0 0-.57-.093c-.49-.044-1.19-.03-2.08.188-1.536.374-3.618 1.343-6.161 3.604l-2.4.238h-.006a2.552 2.552 0 0 0-1.524.734L.15 7.17a.512.512 0 0 0 .433.868l1.896-.271c.28-.04.592.013.955.132.232.076.437.16.655.248l.203.083c.196.816.66 1.58 1.275 2.195.613.614 1.376 1.08 2.191 1.277l.082.202c.089.218.173.424.249.657.118.363.172.676.132.956l-.271 1.9a.512.512 0 0 0 .867.433l2.382-2.386c.41-.41.668-.949.732-1.526l.24-2.408Zm.11-3.699c-.797.8-1.93.961-2.528.362-.598-.6-.436-1.733.361-2.532.798-.799 1.93-.96 2.528-.361.599.599.437 1.732-.36 2.531Z" />
              <path d="M5.205 10.787a7.632 7.632 0 0 0 1.804 1.352c-1.118 1.007-4.929 2.028-5.054 1.903-.126-.127.737-4.189 1.839-5.18.346.69.837 1.35 1.411 1.925Z" />
            </svg>

            <li>
              <a href="{% url 'homepage:main' %}"
                class="nav-link
                {% if view_name == 'homepage:main' %}
                  border text-secondary rounded-2
                {% else %}
                  text-white
                {% endif %}">
                {% trans 'homepage' %}
              </a>
            </li>
            <li>
              <a href="{% url 'about:about' %}"
                class="nav-link
                {% if view_name == 'about:about' %}
                  border text-secondary rounded-2
                {% else %}
                  text-white
                {% endif %}">
                {% trans 'about' %}
              </a>
            </li>
            <li>
              <a href="{% url 'catalog:item_list' %}"
                class="nav-link
                {% if view_name == 'catalog:item_list' %}
                  border text-secondary rounded-2
                {% else %}
                  text-white
                {% endif %}">
                {% trans 'item_list' %}
              </a>
            </li>
            <li>
              <a href="{% url 'feedback:feedback' %}"
                class="nav-link
                {% if view_name == 'feedback:feedback' %}
                  border text-secondary rounded-2
                {% else %}
                  text-white
                {% endif %}">
                {% trans 'feedback' %}
              </a>
            </li>
            {% if request.user.is_superuser %}
              <li>
                <a href="/admin/" class="nav-link navbar-text">{% trans 'administrator' %}</a>
              </li>
            {% endif %}
            {% if request.user.id %}
              <li>
                <a href="{% url "users:profile" %}" class="nav-link navbar-text">{% trans 'profile' %}</a>
              </li>
            {% endif %}
          </nav>
        {% endwith %}
      </div>
    </div>
  </div>
</header>

lyceum/templates/includes/item_card.html
{% block card %}
  <div class="col-3">
    <div class="card custom-gradient-bg" style="width: 18vrem;">
      <div class="card-body">
        {% comment %} {% for image in item.main %}
          <img src="/media/{{image}}" class="card-img-top"/>
        {% empty %} {% endcomment %}
          <div class="alert alert-dark" role="alert">Типа картинка</div>
        {% comment %} {% endfor %} {% endcomment %}
        <h5 class="card-title">{{ item.name }}</h5>
        <div class="card-text">
          Категория: {{item.category.name}}<br/>
          Тэги:{% for tag in item.tags.all %}
            {{ tag }}
          {% endfor %}<br />
          {{ item.text|truncatewords_html:10|safe }}
        </div>
        <a href="{% url 'catalog:item_detail' item.id %}" class="btn btn-primary">{{ item.name }}</a>
      </div>
    </div>
  </div>
{% endblock %}